apiVersion: v1
kind: Service
metadata:
  name: neploy-build-python
spec:
  selector:
    app: neploy-build-python
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP  # Exposes the service on a random node port
